# Generated by Django 5.2.7 on 2025-10-13 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal')),
                ('outflow_type', models.CharField(choices=[('SALE', 'Venda'), ('LOSS', 'Perda / Dano'), ('ADJUSTMENT', 'Ajuste de Estoque')], default='SALE', max_length=20, verbose_name='Tipo de Saída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-created_at'],
            },
        ),
    ]
