# Generated by Django 5.2.7 on 2025-10-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brand_is_active_alter_brand_created_at_and_more'),
        ('categories', '0002_category_is_active_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('serie_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU / Número de Série')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de Venda')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['title'],
            },
        ),
    ]
